# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eed1e5f163078ddda163239103eca00190abdaae72d531ed9a2ff21b16851a9fb913715d39b934eec271218d91f5888f16c4438206326baf5ac0357e7beb6704

test:
  secret_key_base: 335d06267467ce11e4b49b0f7b1ff14bc159bc47767163b75453bc5bb76129c0de94551e46142719666dfd3685da31a7e7a19baf8563a50e8323928b80c8ba51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
