# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 925f4b878a64d3e52b0e31e056d4174149cf5cff6eecba7e03468bcc12bc3fd6ccbbf2c9efcc863f203ee49bab05988bd4139ff728b6fdc7e6c348c386ad9029

test:
  secret_key_base: 117386f5dc75f7f8ca3d6c0592c25bd341c279256bcf5c5fd7cfe0d098ea601208e6db86599cf0caf6260ff708b071fd901ed185821891031a34013eb6841597

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
