# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 838b26ad0415142711e6b6470dad9bbf75df0ba136dc4c13df5d5ac8ec06beb782d222dae3c4ca699c6c0cf6fca53a9b05581415d2a47de54b1a6ca34b5ecd47

test:
  secret_key_base: 2341114c5149a8198f47679e9fac69dd4600f05685389f5c9f82d2c478b1d422a7a9f0197913cde16309bd535574b910ad40a67850f734bef7e66c79d20d8a17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
